### ISSUE TITLE
No marker on front-end if Icon/Image source is not set

### ISSUE THREAD

**Issue by jeanniton-mnr** [graker/mapmarkers#1]
The markers will not be shown on the front-end if you don’t set an image (source) to use as marker 
(contrary to backend which uses the default one).

So that will be good if take these points into account: 
1. Mention that we should set an icon source for the marker to be shown on the front-end in the plugin documentation. Or,
2. Check if a default Icon source is set otherwise use the default one.

Cuz I thought the plugin had some bug and didn’t work.

Thanks!

![map markers](https://user-images.githubusercontent.com/11714176/27883527-c0f2177e-619e-11e7-8eac-4166f50a21a6.png)
![map markers - console](https://user-images.githubusercontent.com/11714176/27883528-c1033022-619e-11e7-849a-5599a78bec9b.png)

**Comment by graker** [comment]
Hi @devmnrj, thanks for bringing this up!
I totally forgot about default icon for the front-end. Will fix this soon.

**Comment by graker** [comment]
And done, now the default marker icon will be used in the absence of a custom one.
