### ISSUE TITLE
What Google API products requires your plugin?

### ISSUE THREAD

**Issue by kanybekovbs** [graker/mapmarkers#4]
Hello. I want to use your plugin in my site and I need to generate Google Maps API key.

Google asks me what products I want to use - Maps, Routes or Places. So can you tell me what options should I select to set your plugin correctly?

Thanks in advance.

**Comment by graker** [comment]
Hey @kanybekovbs 

For my project, I have Maps API enabled. I think that should do. Please reopen if it wasn't enough.

**Comment by kanybekovbs** [comment]
I'm sorry for writing this in the same issue, but I didn't quite understand from the readme:

Can I use your plugin's maps on several pages, so each page should store a list of its markers and display it on its own page?

In other words, can I use your widget as a form widget in my model, so each model entity will keep its own markers?

**Comment by graker** [comment]
No, at the moment you can't filter markers so all maps you create with this plugin's component would display all existing markers.

To implement the feature you described, you'd need to add a property to map component containing an array of marker ids and then fill this property from a model relation.
