### ISSUE TITLE
markersMap component doesn't display on frontend

### ISSUE THREAD

**Issue by afdstudio** [graker/mapmarkers#5]
Is this plugin still working?
I installed on october and everything looks fine on backend and with markerslist.
However, markersMap component doesn't display on frontend.

Thank your for your attention.

**Comment by graker** [comment]
It does. Here's an example https://graker.ru/travel

If you have issues with the component, please provide more information:
 - what kind of errors do you see on screen or in the log?
 - an example of page with the component set up and not showing.

**Comment by graker** [comment]
Also, have you provided Google API key on the backend settings page (backend/system/settings/update/graker/mapmarkers/settings)?

**Comment by afdstudio** [comment]
Hi: Thank you for your fast reply.

API is properly configured on settings.
You can see the frontend page here:
https://www.avminho.com/mapa

Thank you in advance! Regards,

Edgar
Em 21/11/2019, 15:09 +0000, Graker <notifications@github.com>, escreveu:

**Comment by graker** [comment]
Hi, I meant a code example of page having the component :)

**Comment by afdstudio** [comment]
Hi again. Sorry! Here is the code:
——————————————
——————————————


title = “mapa”
url = “/mapa”
layout = “default”
is_hidden = 0

[markersMap]
centerLat = “42,69”
centerLng = “-8,75”
zoom = 2
iconXOffset = 0
iconYOffset = 0
thumbMode = “auto”
thumbWidth = 640
thumbHeight = 480
postPage = “aluguer”
albumPage = “aluguer”
==

<div class="page-container”>

 <div class="container “>

        <div class="row breadcrumbs”>
            <div class="col-md-12 col-sm-12”>
            <h1>Pedido de Fatura</h1>
            </div>
        </div>

        <div class="row corbase”>
   <div class="col-md-12”>

   {% component ‘markersMap’ %}

   </div>
  </div>
</div>
</div>


——————————————
——————————————



Grato pela atenção, cumprimentos,

Edgar Afonso

--------
Afonso Designers, Lda
Rua do Trigo, nr 20
4900-333 Viana do Castelo

tlm: 965601412

www.afonsodesigners.com
Em 21/11/2019, 15:54 +0000, Graker <notifications@github.com>, escreveu:

**Comment by graker** [comment]
Okay thanks, I'll look into it

**Comment by graker** [comment]
Can you please try to add `mapMarker` property to your component's description? Like this:

```
[markersMap]
centerLat = 42
centerLng = 12
zoom = 2
mapMarker = "/themes/grakerru/assets/images/map-marker.png"
iconXOffset = 25
iconYOffset = 25
thumbMode = "crop"
thumbWidth = 160
thumbHeight = 120
postPage = "blog-page"
albumPage = "album"
```

It sets marker icon for the map, you can notice it if you expand the Map Marker item in GUI component settings.

**Comment by afdstudio** [comment]
Hi:

I tried that and everything seems the same.
However, I changed the scripts location and I am getting this error:

[Error] Unhandled Promise Rejection: TypeError: $(this).request is not a function. (In '$(this).request('onDataLoad', {
    success: mapComponentAddMarkers
  })', '$(this).request' is undefined)
	mapComponentInit (mapmarkers_map.js:9)
	(função anónima) (js:140:292)
	(função anónima) (js:140:130)
	promiseReactionJob

Thin it was some conflict with my web scripts.

**Comment by afdstudio** [comment]
Hi again! I deleted the line you gave me and the error disappeared.
However, the map doesn't appear. It is strange because I get the code like this:
(but it not renders)

<img width="461" alt="Captura de ecrã 2019-11-21, às 17 46 33" src="https://user-images.githubusercontent.com/18419250/69362686-e7a93b00-0c86-11ea-8c34-2f0c36052a45.png">

**Comment by graker** [comment]
I think it has maybe something to do with your CSS. Note how the `#mapcomponent` element has `overflow: hidden;` style. Should you remove it manually from browser styles inspector, the map will appear along with the marker. 

Look how in my example https://graker.ru/travel the `#mapcomponent` element and wrapping div have additional styles. Wrapper has width and height specifically set, and mapcomponent has `height: 100%` and `width: auto`. Try to go with something like that.

**Comment by afdstudio** [comment]
Yes; thank you! Some conflict in the CSS. I will fix it!
Thank you for your time!
Can I pay you a cofee? Just send me your paypal account!
Regards!

**Comment by graker** [comment]
No problem :)

I don't use paypal but if you really want to do something, you could just leave a review for this plugin on OctoberCMS market. Thanks!
