### ISSUE TITLE
Error on marker details display

### ISSUE THREAD

**Issue by Zmove** [graker/mapmarkers#6]
Hi, 
I created a map with 2 markers. The map is displaying well, but I get an error when clicking on a marker and it doesn't show the details bubble  : 
`"count(): Parameter must be an array or an object that implements Countable" on line 286 of /var/www/vhosts/sofitness-studio.fr/httpdocs/plugins/graker/mapmarkers/components/Map.php`

![markermap js error](https://user-images.githubusercontent.com/1314678/70316364-d5e59d00-181b-11ea-905d-cbbcff74d21b.png)

Maybe it is related to the component configuration : I don't need to attach any post or album but the components fields are mandatory, so I selected the front page. I doesn't seem to solve the problem anyway. 

![image](https://user-images.githubusercontent.com/1314678/70316649-7340d100-181c-11ea-8208-716434c88aa9.png)

The temporary solution I found is to comment the code of the _getSingleUrl()_ function. But it's not clean and I prefered warn you of the problem to see if we can find a better way out.

Thanks

**Comment by graker** [comment]
Hi @Zmove , thanks for reporting!

Indeed, there's some weirdness in post&album pages selection, although I've managed to create markers without attaching any post and albums. Anyway, you are right and album and post pages shouldn't be mandatory parameters. I'll try to create a fix as soon as I get back from my short vacation.

**Comment by afdstudio** [comment]
Hi! Just facing the same issue! Any update on this? Thank you!

**Comment by graker** [comment]
Hi guys!

Sorry for the delay, didn't have much time to check this out recently.

Is that correct that you use PHP 7.2+? The issue was that since 7.2 it throws warning when trying to `count(NULL)` which might be elevated to exception.

Anyways, could you please check if the latest commit fixes the issue for you? If so, I'll create an update for everyone.

**Comment by graker** [comment]
All right, I'm closing it with an update, feel free to reopen if it doesn't work for you.

**Comment by afdstudio** [comment]
Hi:

Sorry, didn’t had time last week to check this. Will try now.

Thank you!

Edgar

**Comment by graker** [comment]
No worries. As the plugin is updated now on marketplace, you can just run update and don't even replace it with github version.

**Comment by afdstudio** [comment]
Hi! Just updated the plugin and now everything is fine!
Thank you so much!

**Comment by graker** [comment]
That's great to hear!
Thanks for reporting.
